### ISSUE TITLE
Would you mind sharing the dataset "hospdd.csv" ?

### ISSUE THREAD

**Issue by skymagician** [StataMeghan/PyStata#1]

**Comment by StataMeghan** [comment]
All supporting materials have been uploaded:
[https://github.com/StataMeghan/PyStata/blob/main/hospdd.csv](url)

**Comment by skymagician** [comment]
> All supporting materials have been uploaded: [https://github.com/StataMeghan/PyStata/blob/main/hospdd.csv](url)

Thanks
